# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [3]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Hosiyar Singh/Anaconda/Library/include
    lib directory: C:/Users/Hosiyar Singh/Anaconda/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: wind

#### 3. Create a null vector of size 10

In [4]:
arr=np.zeros(10)

#### 4.  How to find the memory size of any array

In [5]:
print(arr.itemsize)

8


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [6]:
np.add?

Signature:       np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\users\hosiyar singh\anaconda\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is Tru

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [7]:
arr1=np.zeros(10);
arr1[4]=1;

#### 7.  Create a vector with values ranging from 10 to 49

In [8]:
arr2=np.arange(10,49)

#### 8.  Reverse a vector (first element becomes last)

In [13]:
arr2=arr2[::-1]
print(arr2)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
arr3=np.arange(0,9)
arr3=arr3.reshape(3,3)
print(arr3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [17]:
arr4=np.array([1,2,0,0,4,0])
for i in range(arr4.size):
    if arr4[i]!=0:
        print(i)

0
1
4


#### 11. Create a 3x3 identity matrix

In [23]:
arr5=np.eye(3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [19]:
arr6=np.random.randn(3,3,3)
print(arr6)

[[[ 0.15063538 -1.57005285  1.57047302]
  [ 0.32700357 -1.59589837 -0.34704852]
  [ 1.99582304 -0.04474829 -0.34859257]]

 [[ 0.40313149 -0.45143363  0.37992837]
  [-1.27916554  1.20298366  0.78291453]
  [ 0.93573335 -0.97493358  0.06104613]]

 [[-1.61401869 -0.6829464   0.50031895]
  [-1.84900223  1.24780803  0.75391078]
  [-0.35358218  1.03716642  1.16178884]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [22]:
arr7=np.random.randn(10,10)
maxi=np.max(arr7)
mini=np.min(arr7)
print(maxi,mini)

1.9417658746306146 -2.3796594496151973


#### 14. Create a random vector of size 30 and find the mean value

In [24]:
arr8=np.random.rand(30)
print(np.mean(arr8))

[0.84311441 0.2416155  0.7671306  0.76264621 0.21837294 0.74126725
 0.4584622  0.87655238 0.10055634 0.16550893 0.25907622 0.38680598
 0.50437212 0.60936697 0.04579082 0.65090046 0.74128091 0.45605139
 0.00860886 0.38216103 0.61826612 0.31276175 0.49301369 0.18504386
 0.62510013 0.65770212 0.40240519 0.30307155 0.35862459 0.35849563]
0.4511375382948354


#### 15. Create a 2d array with 1 on the border and 0 inside

In [29]:
arr9=np.zeros(12)
arr9=arr9.reshape(3,4)
for i in range(3):
    for j in range(4):
        if i==0 or i==2 or j==0 or j==3:
            arr9[i][j]=1;
print(arr9)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [36]:
arr10=[[1,2,3,4],[3,4,5,6]]
arr10=np.pad(arr10,pad_width=1,mode='constant',constant_values=0)
print(arr10)

[[0 0 0 0 0 0]
 [0 1 2 3 4 0]
 [0 3 4 5 6 0]
 [0 0 0 0 0 0]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [37]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(np.nan in set([np.nan]))
print(0.3==3*0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [38]:
arr11=np.zeros((5,5))
for i in range(1,5):
    arr11[i][i-1]=i
print(arr11)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [40]:
arr12=np.zeros((8,8))
arr12[1::2,:: 2]=1
arr12[::2, 1::2]=1;
print(arr12)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [43]:
k=100
d1=6
d2=7
d3=8
x=k/(d2*d3)
y=(k/d3)%d2
z=k%d3
print(int(x),int(y),int(z))

1 5 4
